config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :students do
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of :description, :street, :city, :state, :zip_code
  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name
  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
    @student = Student.find(params[:student_id])
    @address = Address.new
  end

  def create
    student = Student.find(params[:student_id])

    redirect_to student_path(student)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    @student.save
    redirect_to students_path
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    student = Student.find(params[:id])
    student.update(student_params)
    redirect_to student_path(student)
  end

  def destroy
    Student.destroy(params[:id])

    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<h1>Create an address</h1>

<%= form_for [@student, @address] do |f| %>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </p>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </p>
  <p>
    <%= f.submit "submit" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enrollment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav>
  <%= link_to "New Student", new_student_path %>
  <%= link_to "All Students", students_path %>
  </nav>
  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit a student</h1>

<%= form_for(@student) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </p>
  <p>
    <%= f.submit "submit" %>
  </p>
<% end %>

app/views/students/index.html.erb
<h1>Students</h1>

<% @students.each do |student| %>
  <%= student.name %> <%= link_to "Delete", student_path(student), method: :delete %>
  <br>
<% end %>

app/views/students/new.html.erb
<h1>Create a student</h1>

<%= form_for(@student) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/students/show.html.erb
<%= @student.name %>
- <%= link_to "Edit", edit_student_path(@student) %>